import {
  GetObjectCommand,
} from "@aws-sdk/client-s3";

import { S3Client, ListObjectsV2Command } from "@aws-sdk/client-s3";

/**
 * Functions used to access s3
 */

/**
 * Return a list of all keys in an s3 bucket
 * (Generated by Claude)
 */
export const getAllObjectKeys = async (
  s3: S3Client,
  bucket: string
): Promise<string[]> => {
  const objects: string[] = [];
  let continuationToken: string | undefined;

  do {
    const listCmd = new ListObjectsV2Command({
      Bucket: bucket,
      ContinuationToken: continuationToken,
    });

    const response = await s3.send(listCmd);

    // This is the fixed line (type-safe)
    const keys = response.Contents
      ?.map((obj) => obj.Key)
      ?.filter((key): key is string => key != null) || [];

    objects.push(...keys);

    continuationToken = response.NextContinuationToken;
  } while (continuationToken);

  return objects;
};

/**
 * Fetches image binary from an s3 bucket
 * (Generated by Claude)
 */
export const fetchBase64 = async (
  s3: S3Client,
  bucket: string,
  key: string
) => {
  const cmd = new GetObjectCommand({
    Bucket: bucket,
    Key: key,
  });

  const response = await s3.send(cmd);

  // No body → return empty base64 and no metadata
  if (!response.Body) {
    return {
      base64body: "",
      metadata: undefined as Record<string, string> | undefined,
    };
  }

  const byteArray = await response.Body.transformToByteArray();
  const base64body = Buffer.from(byteArray).toString("base64");

  return {
    base64body,           
    metadata: response.Metadata,   // this is Record<string, string> | undefined
  };
};
