/**
 * Helper functions generated by Claude
 */

/**
 * Return a random element in an array
 */
export const getRandomElement = (arr: any[]) =>
  arr[Math.floor(Math.random() * arr.length)]

/**
 * Set difference: returns objects \ exclusionList.
 * All elements in `objects` that are not in `exclusionList`.
 */
export function removeExcluded(objects: string[], exclusionList: string[] | undefined): string[] {
  if (!exclusionList || exclusionList.length === 0) {
    return [...objects];        // return a copy (never mutate the original)
  }

  const excludeSet = new Set(exclusionList);   // O(1) lookups → much faster
  return objects.filter(item => !excludeSet.has(item));
}

export function getRandomElements<T>(list: T[], amount: number): T[] {
  // 1. Handle the case where amount exceeds list length
  if (amount >= list.length) {
    return [...list]; // Return a shallow copy to avoid mutating the original
  }

  // 2. Create a shallow copy and shuffle it
  // We use the Fisher-Yates shuffle algorithm for true randomness
  const shuffled = [...list];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }

  // 3. Return the requested amount
  return shuffled.slice(0, amount);
}