/**
 * Miscellaneous helper functions
 */

import { MetadataRow } from './types';

/**
 * Turn a list of Metadata into a comprehensive object
 */
export function aggregateMetadata(rows: MetadataRow[]) {
    if (!rows.length) {
        return null;
    }
    // Return a list of categories excluding all
    const categories = rows.map((row) => row.category).filter((cat) => cat !== 'all');
    const { category: _category, ...rest } = rows[0];

    return {
        ...rest,
        categories,
    };
}

/**
 * Generator that splits an array into chunks of size `stride`.
 *
 * Adapted from aws-doc-sdk-examples (modified: ported to TypeScript with generics).
 * Source: https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javascriptv3/example_code/libs/utils/util-array.js
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
export function* chunkArray<T>(arr: T[], stride = 1) {
    for (let i = 0; i < arr.length; i += stride) {
        yield arr.slice(i, Math.min(i + stride, arr.length));
    }
}

/**
 * Returns a random element from an array, or undefined if empty.
 */
export function getRandomElement<T>(arr: T[]): T | undefined {
    return arr[Math.floor(Math.random() * arr.length)];
}

/**
 * Returns `amount` random elements from list without repeats
 * (Generated by Claude)
 */
export function getRandomElements<T>(list: T[], amount: number): T[] {
    // 1. Handle the case where amount exceeds list length
    if (amount >= list.length) {
        return [...list]; // Return a shallow copy to avoid mutating the original
    }

    // 2. Create a shallow copy and shuffle it
    // We use the Fisher-Yates shuffle algorithm for true randomness
    const shuffled = [...list];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }

    // 3. Return the requested amount
    return shuffled.slice(0, amount);
}
